apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-demo-prod
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx-demo-prod
  template:
    metadata:
      labels:
        app: nginx-demo-prod
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-demo-prod-service
spec:
  selector:
    app: nginx-demo-prod
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
